### ISSUE TITLE
Showroom doesn't work 

### ISSUE THREAD

**Issue by sensityy** [Sighmir/vrp_adv_garages#1]
When I try to right arrow in the showroom, nothing happens. I don't have any error logs in the console, so I'm a bit lost.. Using vrpex ofcourse.

**Comment by sensityy** [comment]
Yes, default GTA V Cars. https://gyazo.com/b3eb1b566953871c9d7aaa16d4311cce - It looks like it send me to "Garage (BUY)", when I press enter on Showroom, If you look at the top of the menu, is that a mistake?

**Comment by Sighmir** [comment]
No, the showroom is a store, it is intended to say Buy as once in the showroom you will be buying vehicles when pressing enter.

**Comment by Sighmir** [comment]
Have you commented the content of cfg.garages in vrp/cfg/garages.lua?
It should stay similar to this:
```lua
cfg.garages = {
  --{"compacts",-356.146, -134.69, 39.0097},
  --{"coupe",723.013, -1088.92, 22.1829},
  --{"sports",-1145.67, -1991.17, 13.162},
  --{"sportsclassics",1174.76, 2645.46, 37.7545},
  --{"supercars",112.275, 6619.83, 31.8154},
  --{"motorcycles",-205.789, -1308.02, 31.2916}
  --{"planes",1640, 3236, 40.4},
  --{"planes",2123, 4805, 41.19},
  --{"planes",-1348, -2230, 13.9},
  --{"helicopters",1750, 3260, 41.37},
  --{"helicopters",-1233, -2269, 13.9},
  --{"helicopters",-745, -1468, 5},
  --{"boats",-849.5, -1368.64, 1.6},
  --{"boats",1538, 3902, 30.35}
}
```

**Comment by sensityy** [comment]
Well, it worked when I uploaded to my dedicated server, so it's all good now :-) Thanks
